# Generated by Django 3.2.4 on 2022-08-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('mobile', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=70)),
                ('father_name', models.CharField(max_length=70)),
                ('mother_name', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=6)),
                ('dob', models.CharField(max_length=12)),
                ('mail_id', models.EmailField(max_length=254)),
                ('hallticket', models.CharField(max_length=12)),
                ('ration', models.CharField(max_length=14)),
                ('aadhaar', models.CharField(max_length=12)),
                ('address', models.TextField(max_length=200)),
                ('birth_state', models.CharField(max_length=14)),
                ('birth_district', models.CharField(max_length=14)),
                ('category', models.CharField(choices=[('BC-A', 'BC-A'), ('BC-B', 'BC-B'), ('BC-D', 'BC-D'), ('BC-E', 'BC-E'), ('OC', 'OC'), ('SC', 'SC'), ('ST', 'ST')], max_length=10)),
                ('ews', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=6)),
                ('castecert', models.CharField(max_length=14)),
                ('ewscert', models.CharField(max_length=14)),
                ('minority', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=14)),
                ('income', models.CharField(max_length=14)),
                ('incomecert', models.CharField(max_length=14)),
                ('bankac', models.CharField(max_length=14)),
                ('bankifsc', models.CharField(max_length=14)),
                ('hscno', models.CharField(max_length=14)),
                ('village', models.CharField(max_length=14)),
                ('town', models.CharField(max_length=14)),
                ('pincode', models.CharField(max_length=5)),
                ('alt_mobile', models.CharField(max_length=14)),
                ('yop', models.CharField(max_length=4)),
                ('medium', models.CharField(choices=[('TELUGU', 'TELUGU'), ('TELUGU', 'TELUGU')], max_length=6)),
            ],
        ),
    ]
