# Generated by Django 3.2.4 on 2022-08-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSS', '0003_studentdata_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='cat',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='ews',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='medium',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='minority',
            field=models.CharField(default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='ph',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='pref1',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='pref2',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='pref3',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='pref4',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='pref5',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='pref6',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
